# -*- coding: utf-8 -*-
"""Alembic environment — drives migrations against the application's engine.

The database URL and ORM ``target_metadata`` both come from the running
application (``app.database``) so there is a single source of truth for the
schema. This keeps the migration baseline in lock-step with the SQLAlchemy
models and means `alembic upgrade head` and `init_db()` agree on the schema.
"""

from __future__ import annotations

import os
import sys

from alembic import context
from sqlalchemy import engine_from_config, pool

# Make the project root importable so `import app` resolves regardless of CWD.
_PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _PROJECT_ROOT not in sys.path:
    sys.path.insert(0, _PROJECT_ROOT)

# Import AFTER the path is set; these pull in the live engine + Base.metadata.
from app.database import Base, engine  # noqa: E402

config = context.config

# Inject the live DB URL from app config so alembic.ini never holds a hardcoded
# path. This is what lets the same migrations run against the dev DB, the test
# DB (conftest isolation) and a production Postgres (ARCH-10, future).
config.set_main_option("sqlalchemy.url", str(engine.url))

# Best-effort logging setup (don't fail migrations over a logging quirk).
try:
    if config.config_file_name is not None:
        from logging.config import fileConfig
        fileConfig(config.config_file_name)
except Exception:  # pragma: no cover - defensive
    pass

target_metadata = Base.metadata


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode (emit SQL without a DB connection)."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        # render_as_batch lets autogenerated ALTERs work on SQLite (table rebuild).
        render_as_batch=True,
        compare_type=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations against the live engine (used by init_db + CLI)."""
    # Reuse the application's engine rather than building a second one.
    connectable = engine
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            render_as_batch=True,
            compare_type=True,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
